"""Built-in 5-letter English word list for Hurdle legality checks."""

VALID_WORDS: frozenset[str] = frozenset(
    word.upper()
    for word in """
    ABOUT ABOVE ABUSE ACTOR ACUTE ADMIT ADOPT ADULT AFTER AGAIN AGENT AGREE
    AHEAD ALARM ALBUM ALERT ALIEN ALIGN ALIKE ALIVE ALLOW ALONE ALONG ALTER
    AMAZE AMBER AMEND ANGEL ANGER ANGLE ANGRY APART APPLE APPLY ARENA ARGUE
    ARISE ARMOR AROMA AROSE ARRAY ARROW ASIDE ASSET AUDIO AUDIT AVOID AWAKE
    AWARD AWARE BADLY BAKER BASES BASIC BASIS BEACH BEGAN BEGIN BEING BELOW
    BENCH BILLY BIRTH BLACK BLADE BLAME BLANK BLAST BLAZE BLEED BLESS BLIND
    BLOCK BLOOD BLOOM BLOWN BLUES BLUNT BLUSH BOARD BOAST BOBBY BOOST BOOTH
    BOUND BRAIN BRAKE BRAND BRASS BRAVE BREAD BREAK BREED BRIEF BRING BROAD
    BROKE BROWN BRUSH BUDDY BUILD BUILT BUNCH BURST CABLE CALIF CALLS CAMEL
    CANAL CANDY CANOE CARDS CARES CARRY CARVE CATCH CAUSE CHAIN CHAIR CHALK
    CHAMP CHAOS CHARM CHART CHASE CHEAP CHECK CHEEK CHEER CHESS CHEST CHIEF
    CHILD CHINA CHOIR CHOSE CHUNK CIVIC CIVIL CLAIM CLASH CLASS CLEAN CLEAR
    CLERK CLICK CLIFF CLIMB CLING CLOCK CLONE CLOSE CLOTH CLOUD CLOWN COACH
    COAST COULD COUNT COURT COVER CRAFT CRANE CRASH CRAZY CREAM CRIME CROSS
    CROWD CROWN CRUSH CURVE CYCLE DAILY DANCE DATED DEALT DEATH DEBUT DELAY
    DELTA DENSE DEPOT DEPTH DOING DOUBT DOZEN DRAFT DRAIN DRAMA DRANK DRAWN
    DREAM DRESS DRIED DRILL DRINK DRIVE DROVE DROWN DUSTY EAGER EAGLE EARLY
    EARTH EIGHT ELITE EMPTY ENEMY ENJOY ENTER ENTRY EQUAL ERROR EVENT EVERY
    EXACT EXIST EXTRA FAITH FALSE FAULT FIBER FIELD FIFTH FIFTY FIGHT FINAL
    FIRST FIXED FLASH FLEET FLESH FLOAT FLOOD FLOOR FLOUR FLOWN FLUID FOCUS
    FORCE FORTH FORTY FORUM FOUND FRAME FRANK FRAUD FRESH FRONT FROST FRUIT
    FULLY FUNNY GIANT GIVEN GLASS GLOBE GLORY GOING GRACE GRADE GRAIN GRAND
    GRANT GRASS GRAVY GREAT GREEN GROSS GROUP GROWN GUARD GUESS GUEST GUIDE
    HABIT HAPPY HARSH HAVEN HEART HEAVY HENCE HORSE HOTEL HOUSE HUMAN HUMOR
    IDEAL IMAGE INDEX INNER INPUT ISSUE JAPAN JIMMY JOINT JONES JUDGE JUICE
    KNIFE KNOCK KNOWN LABEL LARGE LASER LATER LAUGH LAYER LEARN LEASE LEAST
    LEAVE LEGAL LEVEL LIGHT LIMIT LINKS LIONS LIVES LOCAL LOGIC LOOSE LOWER
    LUCKY LUNCH LYING MAGIC MAJOR MAKER MARCH MATCH MAYBE MAYOR MEANT MEDIA
    METAL METER MIDST MIGHT MINOR MINUS MIXED MODEL MONEY MONTH MORAL MOTOR
    MOUNT MOUSE MOUTH MOVIE MUSIC NEEDS NEVER NEWLY NIGHT NOISE NORTH NOTED
    NOVEL NURSE OCEAN OFFER OFTEN ORDER OTHER OUTER OWNED OWNER PANEL PAPER
    PARTY PEACE PETER PHASE PHONE PHOTO PIANO PIECE PILOT PITCH PLACE PLAIN
    PLANE PLANT PLATE PLAZA POINT POUND POWER PRESS PRICE PRIDE PRIME PRINT
    PRIOR PRIZE PROOF PROUD PROVE QUEEN QUICK QUIET QUITE RADIO RAINY RAISE
    RANGE RAPID RATIO REACH READY REALM REBEL REFER RELAX REPLY RIDER RIDGE
    RIGHT RIVAL RIVER ROBIN ROCKY ROGUE ROMAN ROUGH ROUND ROUTE ROYAL RURAL
    SAUCE SCALE SCARE SCENE SCOPE SCORE SENSE SERVE SEVEN SHADE SHAKE SHALL
    SHAME SHAPE SHARE SHARP SHEET SHELF SHELL SHIFT SHINE SHIRT SHOCK SHOOT
    SHORT SHOWN SIDES SIGHT SILLY SINCE SIXTH SIXTY SIZED SKILL SLEEP SLICE
    SLIDE SMALL SMART SMILE SMOKE SNAKE SOLAR SOLID SOLVE SORRY SOUND SOUTH
    SPACE SPARE SPEAK SPEED SPELL SPEND SPENT SPLIT SPOKE SPORT STAFF STAGE
    STAKE STAND STARK START STATE STEAM STEEL STEEP STEER STICK STILL STOCK
    STONE STOOD STORE STORM STORY STRIP STUCK STUDY STUFF STYLE SUGAR SUITE
    SUPER SWEET TABLE TAKEN TASTE TAXES TEACH TEETH TEMPO THANK THEFT THEIR
    THEME THERE THESE THICK THING THINK THIRD THOSE THREE THREW THROW THUMB
    TIGER TIGHT TIMER TIRED TITLE TODAY TOPIC TOTAL TOUCH TOUGH TOWER TRACK
    TRADE TRAIL TRAIN TRAIT TRASH TREAT TREND TRIAL TRIBE TRICK TRIED TROOP
    TRUCK TRULY TRUNK TRUST TRUTH TWICE TWIST TYLER UNCLE UNDER UNDUE UNION
    UNITY UNTIL UPPER UPSET URBAN USAGE USUAL VALID VALUE VIDEO VIRUS VISIT
    VITAL VOCAL VOICE WASTE WATCH WATER WHEEL WHERE WHICH WHILE WHITE WHOLE
    WHOSE WOMAN WOMEN WORLD WORRY WORSE WORST WORTH WOULD WRITE WRONG WROTE
    YIELD YOUNG YOUTH ZEBRA
    """.split()
)
